[package]
name = "desktop_image_editor"
version = "0.1.0"
description = "This is a desktop application on which we could edit images using opencv etc."
authors = ["iwasakishuto <cabernet.rock@gmail.com>"]
license = "MIT"
repository = "https://github.com/iwasakishuto/desktop-image-editor"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.4", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.5", features = ["api-all"] }
opencv = "0.66"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
